allowBuilds:
  '@reown/appkit': true
  bufferutil: set this to true or false
  keccak: set this to true or false
  protobufjs: true
  sharp: set this to true or false
  unrs-resolver: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@cordystackx/cordy_minikit@2.0.7 || 2.0.9'
